### ISSUE TITLE
kind в examples

### ISSUE THREAD

**Issue by balagurrr** [yandex-cloud/provider-jet-yc#3]
В examples неверно указаны Kind:
FolderIamBinding вместо FolderIAMBinding
FolderIamMember вместо FolderIAMMember
ServiceAccountIamMember вместо ServiceAccountIAMMember

**Comment by vaspahomov** [comment]
Fixed in [872b81f](https://github.com/yandex-cloud/provider-jet-yc/commit/872b81f34a2489cd18c53447c2b7e0070c8e67cb)
